#!/bin/sh

set -x

TMP=/tmp
CLOUDDIR=/root/cloudstack
mkdir -p $TMP/integration-test-results/misc

#STESTS="test_affinity_groups test_deploy_vms_with_varied_deploymentplanners test_disk_offerings test_global_settings test_guest_vlan_range test_iso test_portable_publicip test_primary_storage test_privategw_acl test_public_ip_range test_pvlan test_regions test_reset_vm_on_reboot test_resource_detail test_routers test_secondary_storage test_service_offerings test_ssvm test_templates test_multipleips_per_nic test_network test_non_contigiousvlan test_over_provisioning test_volumes test_vpc_vpn misc/test_deploy_vm test_vm_life_cycle"

CTESTS="test_VirtualRouter_alerts"
#CTESTS="test_VirtualRouter_alerts test_accounts test_acl_isolatednetwork test_acl_isolatednetwork_delete test_acl_listsnapshot test_acl_listvm test_acl_listvolume test_acl_sharednetwork test_acl_sharednetwork_deployVM-impersonation test_add_remove_network test_advancedsg_networks test_affinity_groups test_allocation_states test_asa1000v_fw test_assign_vm test_baremetal test_base_image_updation test_blocker_bugs test_brocade_vcs test_cpu_domain_limits test_cpu_limits test_cpu_max_limits test_cpu_project_limits test_custom_hostname test_deploy_vgpu_vm test_deploy_vm_userdata_reg test_dynamic_compute_offering test_egress_fw_rules test_egress_rules test_eip_elb test_escalations_instances test_escalations_ipaddresses test_escalations_isos test_escalations_networks test_escalations_securitygroups test_escalations_snapshots test_escalations_templates test_escalations_volumes test_escalations_vpncustomergateways test_haproxy test_implicit_planner test_ip_reservation test_lb_secondary_ip test_ldap test_memory_limits test_mm_domain_limits test_mm_max_limits test_mm_project_limits test_multiple_ip_ranges test_multiple_ips_per_nic test_netscaler_configs test_netscaler_lb test_netscaler_lb_algo test_netscaler_lb_sticky test_netscaler_nw_off test_network_offering test_non_contiguous_vlan test_nuage_vsp test_persistent_networks test_portable_ip test_project_configs test_project_limits test_project_resources test_project_usage test_projects test_ps_domain_limits test_ps_limits test_ps_max_limits test_ps_project_limits test_ps_resize_volume test_recurring_snapshots test_redundant_router_cleanups test_redundant_router_services test_redundant_router_upgrades test_region_vpc test_regions test_regions_accounts test_reset_ssh_keypair test_resource_limits test_routers test_security_groups test_shared_networks test_snapshot_gc test_snapshot_limits test_snapshots test_snapshots_improvement test_ss_domain_limits test_ss_limits test_ss_max_limits test_ss_project_limits test_stopped_vm test_storage_motion test_tags test_templates test_update_vm test_usage test_vm_passwdenabled test_vmware_drs test_volumes test_vpc test_vpc_distributed_routing_offering test_vpc_network test_vpc_network_lbrules test_vpc_network_pfrules test_vpc_network_staticnatrule test_vpc_offerings test_vpc_routers test_vpc_vm_life_cycle test_vpc_vms_deployment test_vpn_users"


for suite in $CTESTS; do 
	nosetests --with-xunit --xunit-file=$TMP/integration-test-results/$suite.xml --with-marvin --marvin-config=$CLOUDDIR/setup/dev/advanced.cfg $CLOUDDIR/test/integration/component/$suite.py -s -a tags=advanced,required_hardware=false --zone=Bootcamp --hypervisor=xenserver 
done

#for suite in $STESTS; do 
	#nosetests --with-xunit --xunit-file=$TMP/integration-test-results/$suite.xml --with-marvin --marvin-config=$CLOUDDIR/setup/dev/advanced.cfg $CLOUDDIR/test/integration/smoke/$suite.py -s -a tags=advanced,required_hardware=false --zone=Bootcamp --hypervisor=xenserver 
#done

