SET SQL_SAFE_UPDATES = 0;
INSERT INTO cloud.configuration (category, instance, component, name, value, description) VALUES ("Advanced", "DEFAULT", "management-server", "xen.check.hvm", "false", "Shoud we allow only the XenServers support HVM") on duplicate key update  value="false";
UPDATE cloud.configuration SET value="8096" WHERE name="integration.api.port";
UPDATE cloud.configuration SET value="60" WHERE name="expunge.delay";
UPDATE cloud.configuration SET value="60" WHERE name="expunge.interval";
UPDATE cloud.configuration SET value="60" WHERE name="account.cleanup.interval";
UPDATE cloud.configuration SET value="60" WHERE name="capacity.skipcounting.hours";
UPDATE cloud.configuration SET value="0.99" WHERE name="cluster.cpu.allocated.capacity.disablethreshold";
UPDATE cloud.configuration SET value="0.99" WHERE name="cluster.memory.allocated.capacity.disablethreshold";
UPDATE cloud.configuration SET value="0.99" WHERE name="pool.storage.capacity.disablethreshold";
UPDATE cloud.configuration SET value="0.99" WHERE name="pool.storage.allocated.capacity.disablethreshold";
UPDATE cloud.configuration SET value="60000" WHERE name="capacity.check.period";
UPDATE cloud.configuration SET value="1" WHERE name="event.purge.delay";
UPDATE cloud.configuration SET value="60" WHERE name="network.gc.interval";
UPDATE cloud.configuration SET value="60" WHERE name="network.gc.wait";
UPDATE cloud.configuration SET value="600" WHERE name="vm.op.cleanup.interval";
UPDATE cloud.configuration SET value="60" WHERE name="vm.op.cleanup.wait";
UPDATE cloud.configuration SET value="600" WHERE name="vm.tranisition.wait.interval";
UPDATE cloud.configuration SET value="60" WHERE name="vpc.cleanup.interval";
UPDATE cloud.configuration SET value="4" WHERE name="cpu.overprovisioning.factor";
UPDATE cloud.configuration SET value="8" WHERE name="storage.overprovisioning.factor";
UPDATE cloud.configuration SET value="192.168.217.0/24" WHERE name="secstorage.allowed.internal.sites";
UPDATE cloud.configuration SET value="192.168.217.0/24" WHERE name="management.network.cidr";
UPDATE cloud.configuration SET value="192.168.217.11" WHERE name="host";
UPDATE cloud.configuration SET value="false" WHERE name="check.pod.cidrs";
UPDATE cloud.configuration SET value="0" WHERE name="network.throttling.rate";
UPDATE cloud.configuration SET value="0" WHERE name="vm.network.throttling.rate";
UPDATE cloud.configuration SET value="GMT" WHERE name="usage.execution.timezone";
UPDATE cloud.configuration SET value="16:00" WHERE name="usage.stats.job.exec.time";
UPDATE cloud.configuration SET value="true" WHERE name="enable.dynamic.scale.vm";
UPDATE cloud.configuration SET value="9000" WHERE name="secstorage.vm.mtu.size";
UPDATE cloud.configuration SET value="60" WHERE name="alert.wait";
UPDATE cloud.service_offering SET ram_size="128", speed="128" WHERE vm_type="domainrouter";
UPDATE cloud.service_offering SET ram_size="128", speed="128" WHERE vm_type="elasticloadbalancervm";
UPDATE cloud.service_offering SET ram_size="128", speed="128" WHERE vm_type="secondarystoragevm";
UPDATE cloud.service_offering SET ram_size="128", speed="128" WHERE vm_type="internalloadbalancervm";
UPDATE cloud.service_offering SET ram_size="128", speed="128" WHERE vm_type="consoleproxy";
UPDATE cloud.vm_template SET removed=now() WHERE id="2";
UPDATE cloud.vm_template SET url="http://192.168.217.11/centos56-x86_64.vhd.bz2" WHERE unique_name="centos56-x86_64-xen";
UPDATE cloud.vm_template SET url="http://192.168.217.11/centos55-x86_64.qcow2.bz2" WHERE unique_name="centos55-x86_64";
#http://192.168.217.11/macchinina-xen.vhd.bz2
#UPDATE cloud.configuration SET value="true" WHERE name="system.vm.use.local.storage";
INSERT INTO `cloud`.`vm_template` (uuid, unique_name, name, public, featured, created, state, type, hvm, bits, account_id, url, enable_password, display_text, format, guest_os_id, cross_zones, hypervisor_type, extractable)  VALUES (UUID(), 'CCS Template KVM', 'CCS Template KVM', 1, 1, now(), 'Active', 'BUILTIN', 0, 64, 1, 'http://192.168.217.11/coreos_production_cloudstack_image-kvm.qcow2.bz2',  0, 'Cloudstack Container Service Template (KVM)', 'QCOW2', 99, 1, 'KVM',1);
INSERT INTO `cloud`.`vm_template` (uuid, unique_name, name, public, featured, created, state, type, hvm, bits, account_id, url, enable_password, display_text, format, guest_os_id, cross_zones, hypervisor_type, extractable)  VALUES (UUID(), 'CCS Template Xenserver', 'CCS Template Xenserver', 1, 1, now(), 'Active', 'BUILTIN', 0, 64, 1, 'http://192.168.217.11/coreos_production_cloudstack_image-xen.vhd.bz2',  0, 'Cloudstack Container Service Template (Xenserver)', 'VHD', 99, 1, 'XenServer',1);
UPDATE cloud.configuration SET value="CCS Template Xenserver" WHERE name="cloud.container.cluster.template.name";
